<a href="https://colab.research.google.com/github/phwangktw/ORI390R_queuing_2022_spring/blob/main/optimizer_main_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ciw

In [2]:
pip install pygad

In [3]:
!pip install matplotlib==3.5.1

In [ ]:
import pygad
import numpy

import simulator as sm

# Set cost for deposition to 2, polishing to 1, photo to 8, etch to 5

# function_inputs = [2,1,8,5,2,2,1,8,5,2,1,8,5] #The wieght for each machine type
# desired_output = 500 #The target for obj. function

def fitness_func(solution, solution_idx): #Obj. function, can be modified
    print('Current combination:')
    print(solution)
    output = sm.cost_evaluation(solution)
    print('Cost ='+str(-1*output))
    fitness = 1.0 / output
    
    return fitness

ga_instance = pygad.GA(num_generations=20, #Number of iteration
                       num_parents_mating=4, #Number of parent genes
                       sol_per_pop=50, #Number of offspring per iteration
                       num_genes=13, #Number of genes
                       fitness_func=fitness_func,
                       mutation_type="adaptive", #Increasing mutation to change values
                       mutation_probability=[0.6, 0.2], 

                       init_range_low=1,
                       init_range_high=10,
                       gene_space = [range(1,8),range(1,10),range(6,16),range(3,13),
                                     range(1,10),range(1,8),range(1,11),range(2,12),
                                     range(2,12),range(1,8),range(1,10),range(2,12),
                                     range(3,13)],
                      
                       gene_type=int)

#print(ga_instance.initial_population)
#print(ga_instance.initial_population.shape)
ga_instance.run()
ga_instance.plot_result()
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))

Current combination:
[ 5  5  8 12  6  4 10  9  6  3  2  3  5]
Cost =-565.5264705882353
Current combination:
[4 8 9 5 7 6 9 8 7 4 4 4 6]
Cost =-472.8505294117647
Current combination:
[ 1  9  7 12  1  6  1  9  7  6  6  7  3]
Cost =-799.1268823529413
Current combination:
[ 6  9 12  4  8  1  1  9  8  4  8  3  8]
Cost =-707.7048823529411
Current combination:
[ 7  1  6  3  6  1  9  8  3  6  7 11  9]
Cost =-680.7508823529413
Current combination:
[ 6  9 12 10  4  1  3  6  2  2  9  9 11]
Cost =-664.8247647058823
Current combination:
[ 2  9 11 12  6  2  8  8 11  6  9  7  7]
Cost =-469.58605882352947
Current combination:
[ 4  4 15  4  1  7  7  7  5  1  9  5 12]
Cost =-868.6877058823529
Current combination:
[ 5  9 12 11  1  5  2  5 10  1  5  2 12]
Cost =-839.2105882352939
Current combination:
[ 5  9 11  5  9  5  6  5  4  1  8  8  3]
Cost =-539.335705882353
Current combination:
[ 3  2 15  5  1  4  6  6 11  6  6  5  7]
Cost =-853.0904117647058
Current combination:
[ 2  7  9 12  2  1  3  8  8  2  4  