<a href="https://colab.research.google.com/github/phwangktw/ORI390R_queuing_2022_spring/blob/main/optimizer_main_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ciw

In [2]:
pip install pygad

In [3]:
!pip install matplotlib==3.5.1

In [ ]:
"""
Created on Fri May  6 22:07:41 2022

@author: phwangk

GA optimizer + CIW simulation



"""

import pygad
import numpy

import simulator as sm

# Set cost for deposition to 2, polishing to 1, photo to 8, etch to 5

# function_inputs = [2,1,8,5,2,2,1,8,5,2,1,8,5] #The wieght for each machine type
desired_output = 500 #The target for obj. function

def fitness_func(solution, solution_idx): #Obj. function, can be modified
    print('Current combination:')
    print(solution)
    output = sm.cost_evaluation(solution)
    print('Cost ='+str(-1*output))
    fitness = 1.0 / (numpy.abs(output - desired_output) + 0.000001)
    
    return fitness

ga_instance = pygad.GA(num_generations=20, #Number of iteration
                       num_parents_mating=4, #Number of parent genes
                       sol_per_pop=50, #Number of offspring per iteration
                       num_genes=13, #Number of genes
                       fitness_func=fitness_func,
                       mutation_type="adaptive", #Increasing mutation to change values
                       mutation_probability=[0.6, 0.2], 

                       init_range_low=1,
                       init_range_high=10,
                       gene_space = [range(5, 15), range(5, 15), range(5, 15),
                                    range(5, 15),range(5, 15),range(5, 15),
                                    range(5, 15),range(5, 15),range(5, 15),
                                    range(5, 15),range(5, 15),range(5, 15),
                                    range(5, 15)],
                      
                       gene_type=int)

#print(ga_instance.initial_population)
#print(ga_instance.initial_population.shape)
ga_instance.run()
ga_instance.plot_result()
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))

Current combination:
[ 6 13  8 14  6  7  5 11  8  6  9 11 14]
Cost =705.3996413043479
Current combination:
[ 8  9 10  7  8  7  8 11 14  6 11  8  9]
Cost =560.870347826087
Current combination:
[6 7 6 6 7 6 8 6 8 5 5 8 9]
Cost =618.9669999999999
Current combination:
[13  7  6  8  9 12  7 13 12 10 13  5 11]
Cost =1324.3690652173912
Current combination:
[13 13 12  7  6  9 11  9 11 12 14 12 12]
Cost =606.4195108695652
Current combination:
[ 9  7 10 11  6 11 13  6  6  8 13  5 12]
Cost =1172.0318695652172
Current combination:
[13 13 11 13  5  9 11  9 14  9 12  9 11]
Cost =601.0928260869565
Current combination:
[ 5  9  6  8  7  9 11  9 10 14 12  7 11]
Cost =769.3901630434782
Current combination:
[13  6 14  8  5 13  9  9  9 12 12  7  7]
Cost =788.192402173913
Current combination:
[14 13  8  6 13  7 14  9  7  9  9  9  6]
Cost =882.3410217391305
Current combination:
[ 5 14 12  9  6 14  9  5  7  6 12  6 13]
Cost =954.3933913043479
Current combination:
[ 8  5  6 13 13 11  6 14 14  6  9  6  6]
Cost 